<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <ParallelizeTestCollections>false</ParallelizeTestCollections>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/CompasPb/CompasPb.csproj" />
  </ItemGroup>
</Project>
