<Project>
  <!-- Global properties for all projects -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>

    <!-- Package properties -->
    <Authors>Wei-Ting Chen</Authors>
    <Company>Gramaziokohler</Company>
    <Copyright>Copyright © $(Authors) $([System.DateTime]::Now.Year)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/gramaziokohler/compas_pb_csharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

  </PropertyGroup>

  <!-- Development tools for ALL projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
  </ItemGroup>

  <!-- Test project specific settings -->
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Test project package references -->
  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <IsPackable>false</IsPackable>
    </PackageReference>
  </ItemGroup>

  <!-- Example project settings -->
  <PropertyGroup Condition="$(MSBuildProjectName.Contains('Example')) OR $(MSBuildProjectName.Contains('UserCase'))">
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
