<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup Label="Production Dependencies">
        <PackageVersion Include="Google.Protobuf" Version="3.31.0" />
        <PackageVersion Include="System.Text.Json" Version="9.0.1" />
        <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    </ItemGroup>

    <ItemGroup Label="Build and Versioning">
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.6.143" />
        <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup Label="Testing">
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.3" />
        <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    </ItemGroup>
</Project>
