<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="CompasPb">
            <HintPath>path\to\CompasPb.dll</HintPath>
        </Reference>
        <PackageReference Include="Google.Protobuf" Version="3.31.0" />
    </ItemGroup>
</Project>
