name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # dotnet: ["8.0.x", "9.0.x"]
        os: [ windows-latest ]
        dotnet: ["9.0.x"]

    defaults:
      run:
        working-directory: src/CompasPb

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch comaps_pb_assets
        run: python ../../fetch_compas_pb.py

      - name: .Net Restore
        run: dotnet restore

      - name: .NET Build
        run: dotnet build --no-restore

      - name: .NET Format
        run: dotnet format --verify-no-changes
