name: release

on:
  push:
    tags: ["v*"]

  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run in test mode"
        required: false
        default: "true"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        dotnet: ["9.0.x"]
        framework: [net9.0]
        include:
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-x64

    defaults:
      run:
        working-directory: src/CompasPb

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Determine Version with NBGV
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Display Calculated Version
        run: |
          echo "Calculated Version: ${{ steps.nbgv.outputs.SemVer2 }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Fetch compas_pb_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python ../../fetch_compas_pb.py

      - name: .Net Restore
        run: dotnet restore

      - name: .NET Publish (${{ matrix.os }})
        shell: bash
        run: |
          OUTPUT_PATH="${{ github.workspace }}/release_artifacts/${{ matrix.os }}/${{ matrix.framework }}"
          PROJECT_FILE="${{ github.workspace }}/src/CompasPb/CompasPb.csproj"

          echo "Publishing project: $PROJECT_FILE"
          echo "Publishing to output path: $OUTPUT_PATH"

          # Publish
          dotnet publish "$PROJECT_FILE" -c Release \
            --self-contained true \
            -r ${{ matrix.rid }} \
            -f ${{ matrix.framework }} \
            -o "$OUTPUT_PATH"

          # Get Version
          VERSION_TAG=${{ steps.nbgv.outputs.SemVer2 }}
          FINAL_ARTIFACT_NAME="compas-pb-csharp-${{ matrix.os }}-${{ matrix.framework }}-${VERSION_TAG}"

          echo "Renaming artifact directory to: $FINAL_ARTIFACT_NAME"
          mv "$OUTPUT_PATH" "${{ github.workspace }}/release_artifacts/$FINAL_ARTIFACT_NAME"

          # Pass the new name to the next step
          echo "FINAL_ARTIFACT_NAME=$FINAL_ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compas-pb-csharp-${{ matrix.os }}-${{ matrix.framework }}
          path: ${{ github.workspace }}/release_artifacts/${{ matrix.os }}/${{ matrix.framework }}
          if-no-files-found: error

release:
    needs: [publish]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Determine Version from Tag
        uses: dotnet/nbgv@master
        id: nbgv_release

      - name: Download all published artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: Clean up and Zip Assets
        run: |
          VERSION_TAG=${{ steps.nbgv_release.outputs.SemVer2 }}
          echo "Using Tag Version: $VERSION_TAG"
          cd ./release-assets

          for dir in compas-pb-csharp-*-${VERSION_TAG}; do
              if [ -d "$dir" ]; then
                  Cleaned_Name=$(echo "$dir" | sed "s/compas-pb-csharp-//g")

                  Zip_Name="compas-pb-${VERSION_TAG}-${Cleaned_Name}.zip"

                  echo "Processing artifact: $dir -> $Zip_Name"

                  mv "$dir" "$Cleaned_Name"

                  zip -r "$Zip_Name" "$Cleaned_Name"
                  rm -rf "$Cleaned_Name"
              fi
          done

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*.zip
          name: ${{ github.ref_name }}
          generate_release_notes: true
